// Generated by https://quicktype.io

export interface ImagesTypes {
  id:       string;
  gallery:  string;
  src:      string;
  srcSmall: string;
  prompt:   string;
  width:    number;
  height:   number;
  seed:     string;
  grid:     boolean;
  model:    string;
  guidance: number;
  promptid: string;
  nsfw:     boolean;
}
