export interface TssTypes {
  displayName: string;
  name:        string;
}

// Generated by https://quicktype.io

export interface AllVoices {
  added_at:         number | null;
  architecture:     string;
  category:         string;
  contributors:     string[];
  controls:         boolean;
  display_name:     string;
  is_active:        boolean;
  model_id:         string;
  memberships:      any[];
  is_private:       boolean;
  is_primary:       boolean;
  name:             string;
  symbol_set:       string;
  voicemodel_uuid:  string;
  hifi_gan_vocoder: string;
  ml_model_id:      number;
  speaker_id:       null;
  language:         string;
}

// Generated by https://quicktype.io

export interface ResVoices {
  failed_at:   null;
  finished_at: string;
  path:        string;
  started_at:  string;
  voice_actor: string;
  display_voice: string;
  uuid:        string;
  tts:         string;
  _id:         string;
  createdAt:   string;
  updatedAt:   string;
  __v:         number;
}
